# Generated by Django 3.0.1 on 2019-12-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=10, null=True)),
                ('value', models.CharField(blank=True, max_length=10, null=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Storage',
                'db_table': 'key_value_storage',
            },
        ),
    ]
