# Generated by Django 3.0.1 on 2019-12-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
